export const GREETINGS = [
  "Welcome",
  "Hey",
  "Hello",
  "Welcome Back",
  "Greetings",
  "Hi There",
  "Good To See You",
  "Ready To Learn",
];

export const QUIPS = (studentName) => [
  "Let’s get it done.",
  "Tiny steps count.",
  "One more win today.",
  "You’ve got this.",
  "Progress > perfection.",
  "Consistency beats intensity.",
  "Momentum matters.",
  "Future you will thank you.",
  "Keep the streak alive.",
  "Ship it.",
  "Make it make sense.",
  "Brains on. Let’s go.",
  "Debug first. Panic later.",
  "Compile your thoughts.",
  "One bug at a time.",
  "It works. Don’t touch it.",
  "Push small. Push often.",
  "Don’t forget your journal!",
  "Log it while it’s fresh.",
  "Today counts.",
  "Practice beats theory.",
  "Learn once. Apply twice.",
  "This will click soon.",
  "You’re closer than you think.",
  "Trust the process.",
  `${studentName}, you’re building momentum.`,
  `${studentName}, focus mode: activated.`,
  `Small improvements, big future — ${studentName}.`,
  `Stay consistent, ${studentName}.`,
  `${studentName}, progress looks good on you.`,
  `Lock in, ${studentName}.`,
  `${studentName}, think like an engineer.`,
  `Future ${studentName} appreciates this.`,
  `Level up, ${studentName}.`,
  `${studentName}, earn the streak.`,
  `Keep your standards high, ${studentName}.`,
  `${studentName}, discipline > motivation.`,
  `${studentName}, master the basics.`,
  `${studentName}, stay curious.`,
];